---
version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - heimdall-data:/config
    ports:
      - 9999:80
    restart: always
